using System;
using System.Collections.Generic;

namespace ZeusInventarioWebAPI.Models
{
    public partial class MovimientoItem
    {
        public decimal CodigoDocuItem { get; set; }
        public decimal? Aprobado { get; set; }
        public decimal TipoDocumento { get; set; }
        public decimal CodigoDocumento { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Faltantes { get; set; }
        public double ValorUnidad { get; set; }
        public decimal PorcentajeDcto { get; set; }
        public decimal PorcentajeIva { get; set; }
        public decimal FletesUnidad { get; set; }
        public DateTime? DiasGarantia { get; set; }
        public decimal CodigoItem { get; set; }
        public string CodigoArticulo { get; set; } = null!;
        public string? CodigoLote { get; set; }
        public string? CodigoBodega { get; set; }
        public decimal? CodigoClasificacion { get; set; }
        public string? NombreArticulo { get; set; }
        public string? NombreBodega { get; set; }
        public string? NombreLote { get; set; }
        public string? NombreClasificacion { get; set; }
        public string Serial { get; set; } = null!;
        public string? CodigoUbicacion { get; set; }
        public string? NombreUbicacion { get; set; }
        public decimal IdArticulo { get; set; }
        public string? Presentacion { get; set; }
        public decimal Porcentajeimp { get; set; }
        public decimal PrecioEnOtraMoneda { get; set; }
        public bool Descargardeinventarios { get; set; }
        public decimal PrecioUnidad { get; set; }
        public string Detalle { get; set; } = null!;
        public decimal TotalIvacompras { get; set; }
        public decimal TotalIvaventas { get; set; }
        public decimal TotalIvaconsumo { get; set; }
        public decimal TotalDescuentoCompra { get; set; }
        public decimal TotalDescuentoVenta { get; set; }
        public decimal CostoTotal { get; set; }
        public decimal PrecioTotal { get; set; }
        public decimal PrecioTotalEnOtraMoneda { get; set; }
        public decimal PorcentajeIvamaxDeducible { get; set; }
        public decimal? Ordengrabacion { get; set; }
        public decimal? ItemsRelacionado { get; set; }
        public bool? CostoAjustado { get; set; }
        public decimal? TasaCambioItems { get; set; }
        public double? ValorUnidadOtraMoneda { get; set; }
        public decimal? PorcentajeimpuestoOtraMoneda { get; set; }
        public decimal? OtrosCostosOtraMoneda { get; set; }
        public decimal? CostoTotalOtraMoneda { get; set; }
        public decimal? TotalDescuentoCompraOtraMoneda { get; set; }
        public decimal? TotalDescuentoVentaOtraMoneda { get; set; }
        public decimal? TotalIvacomprasOtraMoneda { get; set; }
        public decimal? TotalIvaventasOtraMoneda { get; set; }
        public decimal? PrecioTotalReal { get; set; }
        public decimal? PesoRealPorcionamiento { get; set; }
        public bool? ArticuloIndirectoNoValorizaFormula { get; set; }
        public int? TiempoDeEntrega { get; set; }
        public string? CodigoReferencia { get; set; }
        public string? NombreReferencia { get; set; }
        public decimal CantidadPerdida { get; set; }
        public decimal? ConsecutivoVariables { get; set; }
        public decimal? PrecioxLote { get; set; }
        public decimal? TasaCalculo { get; set; }
        public string? IdProveedor { get; set; }
        public decimal? PrecioProveedor { get; set; }
        public decimal? RentabilidadProveedor { get; set; }
        public decimal? PorcentajeIvaProvision { get; set; }
        public decimal? ImpoConPorcentaje { get; set; }
        public decimal? ImpoConPorcentajeMaximoDescontable { get; set; }
        public decimal? TotalImpoConCompras { get; set; }
        public decimal? TotalImpoConVentas { get; set; }
        public decimal? TotalImpoConComprasOtraMoneda { get; set; }
        public decimal? TotalImpoConVentasOtraMoneda { get; set; }
        public decimal? TotalIvadescontable { get; set; }
        public decimal? TotalImpoConDescontable { get; set; }
        public double TasaNiif { get; set; }
        public double ValorUnidad2 { get; set; }
        public decimal CostoTotal2 { get; set; }
        public decimal? FletesUnidad2 { get; set; }
        public decimal? PrecioUnidad2 { get; set; }
        public decimal? PrecioTotal2 { get; set; }
        public decimal? TotalIvacompras2 { get; set; }
        public decimal? TotalIvaventas2 { get; set; }
        public decimal? TotalIvaconsumo2 { get; set; }
        public decimal? TotalDescuentoCompra2 { get; set; }
        public decimal? TotalDescuentoVenta2 { get; set; }
        public decimal? ValorImpuestoConsumo2 { get; set; }
        public decimal? TotalImpoConCompras2 { get; set; }
        public decimal? TotalImpoConVentas2 { get; set; }
        public decimal? TotalIvadescontable2 { get; set; }
        public decimal? TotalImpoConDescontable2 { get; set; }
        public decimal? TotalDescuentoFinanciero { get; set; }
        public decimal? TotalDescuentoFinanciero2 { get; set; }
        public string? ContabilizaDescuentoFinanciero { get; set; }
        public decimal? EscenariosTributarioConsumoIden { get; set; }
        public decimal? EscenariosTributarioRentaIden { get; set; }
        public decimal? EscenariosSubCategoriaEfecCompraIden { get; set; }
        public decimal? EscenariosEscenarioIden { get; set; }
        public decimal? Ciudad { get; set; }
        public int? AutoGenerado { get; set; }
        public string? Linea { get; set; }
        public string? SubLinea { get; set; }
        public DateTime? FechaEntrega { get; set; }
        public string? DireccionEntrega { get; set; }
        public string? RubroPresu { get; set; }
        public string? ReservaPresu { get; set; }
        public decimal? PorcentajeDctoConfidencial { get; set; }
        public decimal? TotalDctoConfidencial { get; set; }
        public decimal? ValorUnidadInc { get; set; }
        public decimal Consecutivo { get; set; }
        public decimal CodigoTipoDocumento { get; set; }
        public string? NombreTipoDocumento { get; set; }
        public DateTime FechaDocumento { get; set; }
        public DateTime? FechaRequerida { get; set; }
        public string Estado { get; set; } = null!;
        public string? Fuente { get; set; }
        public string? Serie { get; set; }
        public string? Documento { get; set; }
        public decimal? Usuario { get; set; }
        public string? DetalleDocumento { get; set; }
        public string? Tercero { get; set; }
        public byte? TipoTercero { get; set; }
        public string? NombreTercero { get; set; }
        public string? DocumentoTercero { get; set; }
        public decimal? Solicitante { get; set; }
        public string? NombreSolicitante { get; set; }
        public decimal? Departamento { get; set; }
        public string? NombreDepartamento { get; set; }
        public string Grupo { get; set; } = null!;
        public string? NombreGrupo { get; set; }
        public decimal? Factor { get; set; }
        public bool? Anticipo { get; set; }
        public decimal? ValorAnticipo { get; set; }
        public string? FormaPago { get; set; }
        public string? CuentaPago { get; set; }
        public string? Moneda { get; set; }
        public decimal TasaCambio { get; set; }
        public string? CentroCosto { get; set; }
        public decimal? Aprueba { get; set; }
        public string? Vendedor { get; set; }
        public string? SubOrden { get; set; }
        public decimal? Numerocuotas { get; set; }
        public DateTime? Vencimientoinicial { get; set; }
        public decimal? Diascreditos { get; set; }
        public string? NombreVendedor { get; set; }
        public string? TipoFactura { get; set; }
        public string? DespachoCliente { get; set; }
        public string? DespachoDireccion { get; set; }
        public string? DespachoCiudad { get; set; }
        public string? DespachoTransportadora { get; set; }
        public DateTime? Fechafactura { get; set; }
        public string? Caja { get; set; }
        public decimal? Cajero { get; set; }
        public string? Jornada { get; set; }
        public bool? EntregaConCupo { get; set; }
        public int? Condicion { get; set; }
        public string? TipoRemision { get; set; }
        public string? UsuarioServicio { get; set; }
        public string? PrestadorServicio { get; set; }
        public decimal? Cargo1 { get; set; }
        public decimal? Cargo2 { get; set; }
        public decimal? Cargo3 { get; set; }
        public decimal? DocumentoConPendiente { get; set; }
        public string? EstadoExterno { get; set; }
        public decimal? Aplicacion { get; set; }
        public decimal? TipoDocumentoExterno { get; set; }
        public decimal? ConsecutivoExterno { get; set; }
        public string? NombreCaja { get; set; }
        public string? NombreCajero { get; set; }
        public string? NombreJornada { get; set; }
        public string? NombreUsuarioServicio { get; set; }
        public string? NombrePrestadorServicio { get; set; }
        public string? Ncf { get; set; }
        public string? NcfModificado { get; set; }
        public string? ModalidadVentas { get; set; }
        public string? CuentaAnticipo { get; set; }
        public string? Auxiliar { get; set; }
        public bool? ProvisionProveedores { get; set; }
        public string? Bu { get; set; }
        public decimal? ConsecutivoBu { get; set; }
    }
}
